export default {
    "Alsace": 8,
    "Aquitaine": 8,
    "Auvergne": 8,
    "Bourgogne": 8,
    "Bretagne": 20,
    "Centre-Val-de-Loire": 8,
    "Champagne-Aredenne": 8,
    "Corse": 8,
    "Cote d'azur": 8,
    "Franche-Comté": 8,
    "Guadeloupe": 8,
    "Guyane": 8,
    "Île-de-France": 8,
    "Languedoc-Roussillon": 8,
    "Limousin": 8,
    "Lorraine": 8,
    "Martinique": 8,
    "Mayotte": 8,
    "Midi-Pyrénées": 8,
    "Nord-Pas-de-Calais": 8,
    "Normandie":8,
    "Nouvelle-Caledonie": 8,
    "Pays de la Loire": 8,
    "Picardie": 8,
    "Poitou-Charentes": 8,
    "Provence": 8,
    "Reunion": 8,
    "Rhône-Alpes": 8,
    "Wallis et Futuna": 8
  }